### ISSUE TITLE
Events CRUD required

### ISSUE THREAD

**Issue by WillCWX** [ChubbsBunns/Kakilang#23]
The events page needs CRUD:

- [x] Creation of Events Page #24 
- [x] Reading of Events Page #26 
- [x] Updating of Events Page #27 
- [x] Deletion of Events Page #28 

Each will be a separate issue.

**Comment by WillCWX** [comment]
Currently completed with client-side security.
Server-side security will be updated later.
